import { defineStore } from 'pinia'
import { ref } from 'vue'

export type Language = 'ar' | 'ckb'

export const useLanguageStore = defineStore('language', () => {
  const currentLanguage = ref<Language>('ckb')

  const texts = {
    ar: {
      // Login page
      welcomeBack: 'مرحباً بك!',
      loginSubtitle: 'سجل دخولك للحصول على وصول غير محدود للبيانات والمعلومات',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      rememberMe: 'تذكرني',
      forgotPassword: 'نسيت كلمة المرور؟',
      login: 'تسجيل الدخول',
      loginWith: 'أو، سجل الدخول بـ',
      googleLogin: 'تسجيل الدخول بـ Google',
      noAccount: 'ليس لديك حساب؟',
      registerHere: 'سجل هنا',

      // Dashboard
      dashboard: 'لوحة التحكم',
      welcomeToDashboard: 'مرحباً بك في نظام إدارة تعلم العربية',
      totalStudents: 'إجمالي الطلاب',
      totalExams: 'إجمالي الاختبارات',
      activeExams: 'الاختبارات النشطة',
      completedExams: 'الاختبارات المكتملة',
      pendingRequests: 'طلبات في الانتظار',
      teachingMaterials: 'المواد التعليمية',
      averageScore: 'متوسط النتيجة',
      todayRegistrations: 'تسجيلات اليوم',
      loading: 'جاري التحميل',
      justNow: 'الآن',
      minutesAgo: 'دقيقة',
      hoursAgo: 'ساعة',
      daysAgo: 'يوم',

      // Navigation
      mainMenu: 'القائمة الرئيسية',
      studentManagement: 'إدارة الطلاب',
      students: 'الطلاب',
      registrationRequests: 'طلبات التسجيل',
      examManagement: 'إدارة الاختبارات',
      exams: 'الاختبارات',
      createExam: 'إنشاء اختبار',
      examResults: 'نتائج الاختبارات',
      materials: 'المواد التعليمية',
      uploadMaterials: 'رفع مواد جديدة',

      // Dashboard specific
      recentActivity: 'النشاط الأخير',
      quickActions: 'إجراءات سريعة',
      createNewExam: 'إنشاء اختبار جديد',
      uploadTeachingMaterials: 'رفع مواد تعليمية',
      reviewRegistrationRequests: 'مراجعة طلبات التسجيل',
      viewReports: 'عرض التقارير',
      noRecentActivity: 'لا توجد نشاطات حديثة',
      addNewStudent: 'إضافة طالب جديد',

      // Students page
      addStudent: 'إضافة طالب',
      editStudent: 'تعديل الطالب',
      deleteStudent: 'حذف الطالب',
      viewStudent: 'عرض الطالب',
      studentName: 'اسم الطالب',
      studentEmail: 'بريد الطالب الإلكتروني',
      studentPhone: 'هاتف الطالب',
      educationLevel: 'المستوى التعليمي',
      motivation: 'الدافع',
      status: 'الحالة',
      registrationDate: 'تاريخ التسجيل',
      actions: 'الإجراءات',
      searchStudents: 'البحث في الطلاب',
      filterByStatus: 'تصفية حسب الحالة',
      all: 'الكل',
      active: 'نشط',
      inactive: 'غير نشط',
      pending: 'في الانتظار',
      suspended: 'معلق',

      // Pending students
      approveStudent: 'الموافقة على الطالب',
      rejectStudent: 'رفض الطالب',
      approveAllSelected: 'الموافقة على المحددين',
      rejectAllSelected: 'رفض المحددين',
      selectAll: 'تحديد الكل',
      selected: 'محدد',
      approve: 'موافقة',
      reject: 'رفض',
      approvalReason: 'سبب الموافقة',
      rejectionReason: 'سبب الرفض',

      // Materials page
      addMaterial: 'إضافة مادة',
      editMaterial: 'تعديل المادة',
      deleteMaterial: 'حذف المادة',
      viewMaterial: 'عرض المادة',
      materialTitle: 'عنوان المادة',
      materialDescription: 'وصف المادة',
      sectionName: 'اسم القسم',
      category: 'الفئة',
      fileType: 'نوع الملف',
      fileSize: 'حجم الملف',
      downloadCount: 'عدد التحميلات',
      isPublic: 'عام',
      tags: 'العلامات',
      searchMaterials: 'البحث في المواد',
      filterByCategory: 'تصفية حسب الفئة',
      filterByType: 'تصفية حسب النوع',
      pdf: 'PDF',
      image: 'صورة',
      video: 'فيديو',
      audio: 'صوت',
      youtube: 'يوتيوب',
      text: 'نص',

      // Upload materials
      uploadNewMaterial: 'رفع مادة جديدة',
      materialType: 'نوع المادة',
      fileUpload: 'رفع ملف',
      youtubeLink: 'رابط يوتيوب',
      textContent: 'محتوى نصي',
      chooseFile: 'اختر ملف',
      dragDropFile: 'اسحب وأفلت الملف هنا',
      or: 'أو',
      browseFiles: 'تصفح الملفات',
      youtubeUrl: 'رابط يوتيوب',
      contentText: 'النص',
      privacySettings: 'إعدادات الخصوصية',
      public: 'عام',
      private: 'خاص',
      saveDraft: 'حفظ كمسودة',
      publish: 'نشر',
      reset: 'إعادة تعيين',

      // Additional upload materials
      addNewTeachingMaterial: 'إضافة مادة تعليمية جديدة',
      backToMaterials: 'العودة إلى المواد',
      materialInformation: 'معلومات المادة',
      title: 'العنوان',
      uploadType: 'نوع الرفع',
      uploadFile: 'رفع ملف',
      uploadFileDescription: 'رفع ملف PDF أو صورة أو فيديو',
      uploadYouTube: 'رابط يوتيوب',
      uploadYouTubeDescription: 'إضافة رابط فيديو من يوتيوب',
      uploadText: 'محتوى نصي',
      uploadTextDescription: 'إضافة محتوى نصي مباشرة',
      sectionNameHint: 'اسم القسم أو الفصل الدراسي',
      tagsHint: 'فصل العلامات بفواصل (مثال: قواعد، مفردات، قراءة)',
      descriptionHint: 'وصف مفصل للمادة التعليمية',
      fileTooLarge: 'الملف كبير جداً. الحد الأقصى 50 ميجابايت',
      invalidFileType: 'نوع الملف غير مدعوم',
      materialUploaded: 'تم رفع المادة بنجاح',
      errorUploadingMaterial: 'حدث خطأ في رفع المادة',
      draftSaved: 'تم حفظ المسودة',
      errorSavingDraft: 'حدث خطأ في حفظ المسودة',

      // Exams page
      addExam: 'إضافة اختبار',
      editExam: 'تعديل الاختبار',
      deleteExam: 'حذف الاختبار',
      viewExam: 'عرض الاختبار',
      examTitle: 'عنوان الاختبار',
      examDescription: 'وصف الاختبار',
      difficulty: 'الصعوبة',
      duration: 'المدة (دقائق)',
      startDate: 'تاريخ البداية',
      endDate: 'تاريخ النهاية',
      passingScore: 'النتيجة المطلوبة للنجاح',
      attemptsAllowed: 'عدد المحاولات المسموحة',
      showResults: 'إظهار النتائج',
      allowReview: 'السماح بالمراجعة',
      randomizeQuestions: 'ترتيب الأسئلة عشوائياً',
      timeLimit: 'حد زمني',
      examStatus: 'الحالة',
      draft: 'مسودة',
      examActive: 'نشط',
      examCompleted: 'مكتمل',
      archived: 'مؤرشف',
      easy: 'سهل',
      medium: 'متوسط',
      hard: 'صعب',
      searchExams: 'البحث في الاختبارات',
      filterByDifficulty: 'تصفية حسب الصعوبة',
      filterByStatus: 'تصفية حسب الحالة',

      // Create exam page
      basicInformation: 'المعلومات الأساسية',
      description: 'الوصف',
      titleRequired: 'العنوان مطلوب',
      difficultyRequired: 'مستوى الصعوبة مطلوب',
      durationRequired: 'المدة مطلوبة',
      publishExam: 'نشر الاختبار',
      questions: 'الأسئلة',
      addQuestion: 'إضافة سؤال',
      questionText: 'نص السؤال',
      questionType: 'نوع السؤال',
      multipleChoice: 'اختيار متعدد',
      trueFalse: 'صح وخطأ',
      points: 'النقاط',
      options: 'الخيارات',
      addOption: 'إضافة خيار',
      correctAnswer: 'الإجابة الصحيحة',
      questionRequired: 'نص السؤال مطلوب',
      atLeastTwoOptions: 'يجب أن يكون هناك خياران على الأقل',
      completeAllQuestions: 'يرجى إكمال جميع الأسئلة',
      examPublished: 'تم نشر الاختبار بنجاح',
      addAtLeastOneQuestion: 'يجب إضافة سؤال واحد على الأقل',
      minutes: 'دقيقة',

      // Exam results
      examResults: 'نتائج الاختبار',
      selectExam: 'اختر الاختبار',
      totalParticipants: 'إجمالي المشاركين',
      passedStudents: 'الطلاب الناجحون',
      failedStudents: 'الطلاب الراسبون',
      exportResults: 'تصدير النتائج',
      studentName: 'اسم الطالب',
      score: 'النتيجة',
      percentage: 'النسبة المئوية',
      attemptNumber: 'رقم المحاولة',
      startTime: 'وقت البداية',
      endTime: 'وقت النهاية',
      attemptStatus: 'الحالة',
      inProgress: 'قيد التنفيذ',
      attemptCompleted: 'مكتمل',
      abandoned: 'متروك',

      // Additional exam results
      viewExamResults: 'عرض نتائج الاختبار',
      backToExams: 'العودة إلى الاختبارات',
      chooseExam: 'اختر الاختبار',
      noResults: 'لا توجد نتائج',
      noResultsDescription: 'لم يتم العثور على نتائج لهذا الاختبار',
      exportFeature: 'ميزة التصدير قيد التطوير',
      viewAttemptDetails: 'عرض تفاصيل المحاولة',
      attemptDetailsStudent: 'عرض تفاصيل محاولة الطالب',

      // Messages
      loginSuccess: 'تم تسجيل الدخول بنجاح',
      logoutSuccess: 'تم تسجيل الخروج بنجاح',
      fillAllFields: 'يرجى ملء جميع الحقول المطلوبة',
      operationSuccess: 'تمت العملية بنجاح',
      operationFailed: 'فشلت العملية',
      confirmDelete: 'هل أنت متأكد من الحذف؟',
      confirmAction: 'هل أنت متأكد من هذا الإجراء؟',
      yes: 'نعم',
      no: 'لا',

      // General
      profile: 'الملف الشخصي',
      role: 'الدور',
      logout: 'تسجيل الخروج',
      close: 'إغلاق',
      cancel: 'إلغاء',
      save: 'حفظ',
      edit: 'تعديل',
      delete: 'حذف',
      view: 'عرض',
      download: 'تحميل',
      search: 'بحث',
      filter: 'تصفية',
      clear: 'مسح',
      submit: 'إرسال',
      back: 'رجوع',
      next: 'التالي',
      previous: 'السابق',
      finish: 'إنهاء',

      // Additional translations
      required: 'مطلوب',
      passwordRequired: 'كلمة المرور مطلوبة',
      fullName: 'الاسم الكامل',
      nameRequired: 'الاسم مطلوب',
      emailRequired: 'البريد الإلكتروني مطلوب',
      createAccount: 'إنشاء حساب جديد',
      createAccountSuccess: 'تم إنشاء الحساب بنجاح. يرجى التحقق من بريدك الإلكتروني',
      googleLoginComingSoon: 'سيتم إضافة تسجيل الدخول بـ Google قريباً',
      fillAllFieldsRequired: 'يرجى ملء جميع الحقول المطلوبة'
    },
    ckb: {
      // Login page
      welcomeBack: 'بەخێربێیتەوە!',
      loginSubtitle: 'بچۆرە ژوورەوە بۆ دەستپێگەیشتنی سنووردار بە داتا و زانیاریەکان',
      email: 'ئیمەیڵ',
      password: 'وشەی نهێنی',
      rememberMe: 'لەبیرم بکە',
      forgotPassword: 'وشەی نهێنیت لەبیر کردووە؟',
      login: 'چوونە ژوورەوە',
      loginWith: 'یان، بچۆرە ژوورەوە بە',
      googleLogin: 'چوونە ژوورەوە بە Google',
      noAccount: 'هیچ هەژماریت نییە؟',
      registerHere: 'لێرە تۆمار بکە',

      // Dashboard
      dashboard: 'داشبۆرد',
      welcomeToDashboard: 'بەخێربێیت بۆ سیستەمی بەڕێوەبردنی فێربوونی عەرەبی',
      totalStudents: 'کۆی قوتابیان',
      totalExams: 'کۆی تاقیکردنەوەکان',
      activeExams: 'تاقیکردنەوە چالاکەکان',
      completedExams: 'تاقیکردنەوە تەواوکراوەکان',
      pendingRequests: 'داواکاریەکانی چاوەڕوان',
      teachingMaterials: 'ماددەی فێرکاری',
      averageScore: 'تێکڕای نمرە',
      todayRegistrations: 'تۆمارکردنەکانی ئەمڕۆ',
      loading: 'چاوەڕوان بە',
      justNow: 'ئێستا',
      minutesAgo: 'خولەک',
      hoursAgo: 'کاتژمێر',
      daysAgo: 'ڕۆژ',

      // Navigation
      mainMenu: 'مینووی سەرەکی',
      studentManagement: 'بەڕێوەبردنی قوتابیان',
      students: 'قوتابیان',
      registrationRequests: 'داواکاری تۆمارکردن',
      examManagement: 'بەڕێوەبردنی تاقیکردنەوە',
      exams: 'تاقیکردنەوەکان',
      createExam: 'دروستکردنی تاقیکردنەوە',
      examResults: 'ئەنجامی تاقیکردنەوەکان',
      materials: 'ماددەی فێرکاری',
      uploadMaterials: 'بارکردنی ماددەی نوێ',

      // Dashboard specific
      recentActivity: 'چالاکی دواخ',
      quickActions: 'کردارە خێراکان',
      createNewExam: 'دروستکردنی تاقیکردنەوەی نوێ',
      uploadTeachingMaterials: 'بارکردنی ماددەی فێرکاری',
      reviewRegistrationRequests: 'پێداچوونەوەی داواکاری تۆمارکردن',
      viewReports: 'بینینی ڕاپۆرتەکان',
      noRecentActivity: 'هیچ چالاکیەکی دواخ نییە',
      addNewStudent: 'زیادکردنی قوتابیێکی نوێ',

      // Students page
      addStudent: 'زیادکردنی قوتابی',
      editStudent: 'دەستکاریکردنی قوتابی',
      deleteStudent: 'سڕینەوەی قوتابی',
      viewStudent: 'بینینی قوتابی',
      studentName: 'ناوی قوتابی',
      studentEmail: 'ئیمەیڵی قوتابی',
      studentPhone: 'ژمارەی مۆبایلی قوتابی',
      educationLevel: 'ئاستی خوێندن',
      motivation: 'هۆکار',
      status: 'دۆخ',
      registrationDate: 'بەرواری تۆمارکردن',
      actions: 'کردارەکان',
      searchStudents: 'گەڕان بۆ قوتابیان',
      filterByStatus: 'فلتەرکردن بەپێی دۆخ',
      all: 'هەموو',
      active: 'چالاک',
      inactive: 'ناچالاک',
      pending: 'چاوەڕوان',
      suspended: 'هەڵواسراو',

      // Pending students
      approveStudent: 'پەسەندکردنی قوتابی',
      rejectStudent: 'ڕەتکردنەوەی قوتابی',
      approveAllSelected: 'پەسەندکردنی هەڵبژێردراوەکان',
      rejectAllSelected: 'ڕەتکردنەوەی هەڵبژێردراوەکان',
      selectAll: 'هەڵبژاردنی هەموو',
      selected: 'هەڵبژێردراو',
      approve: 'پەسەندکردن',
      reject: 'ڕەتکردنەوە',
      approvalReason: 'هۆکاری پەسەندکردن',
      rejectionReason: 'هۆکاری ڕەتکردنەوە',

      // Materials page
      addMaterial: 'زیادکردنی ماددە',
      editMaterial: 'دەستکاریکردنی ماددە',
      deleteMaterial: 'سڕینەوەی ماددە',
      viewMaterial: 'بینینی ماددە',
      materialTitle: 'ناونیشانی ماددە',
      materialDescription: 'وەسفی ماددە',
      sectionName: 'ناوی بەش',
      category: 'پۆل',
      fileType: 'جۆری فایل',
      fileSize: 'قەبارەی فایل',
      downloadCount: 'ژمارەی داگرتن',
      isPublic: 'گشتی',
      tags: 'تاگەکان',
      searchMaterials: 'گەڕان بۆ ماددەکان',
      filterByCategory: 'فلتەرکردن بەپێی پۆل',
      filterByType: 'فلتەرکردن بەپێی جۆر',
      pdf: 'PDF',
      image: 'وێنە',
      video: 'ڤیدیۆ',
      audio: 'دەنگ',
      youtube: 'یوتیوب',
      text: 'دەق',

      // Upload materials
      uploadNewMaterial: 'بارکردنی ماددەی نوێ',
      materialType: 'جۆری ماددە',
      fileUpload: 'بارکردنی فایل',
      youtubeLink: 'لینکی یوتیوب',
      textContent: 'ناوەڕۆکی دەق',
      chooseFile: 'هەڵبژاردنی فایل',
      dragDropFile: 'فایلەکە لێرە بکێشە و بەڕێوە',
      or: 'یان',
      browseFiles: 'گەڕان بۆ فایلەکان',
      youtubeUrl: 'لینکی یوتیوب',
      contentText: 'دەق',
      privacySettings: 'ڕێکخستنەکانی تایبەتمەندی',
      public: 'گشتی',
      private: 'تایبەت',
      saveDraft: 'پاشەکەوتکردن وەک ڕەشنووس',
      publish: 'بڵاوکردنەوە',
      reset: 'ڕێکخستنەوە',

      // Additional upload materials
      addNewTeachingMaterial: 'زیادکردنی ماددەیەکی فێرکاری نوێ',
      backToMaterials: 'گەڕانەوە بۆ ماددەکان',
      materialInformation: 'زانیاری ماددە',
      title: 'ناونیشان',
      uploadType: 'جۆری بارکردن',
      uploadFile: 'بارکردنی فایل',
      uploadFileDescription: 'بارکردنی فایلی PDF یان وێنە یان ڤیدیۆ',
      uploadYouTube: 'لینکی یوتیوب',
      uploadYouTubeDescription: 'زیادکردنی لینکی ڤیدیۆ لە یوتیوب',
      uploadText: 'ناوەڕۆکی دەق',
      uploadTextDescription: 'زیادکردنی ناوەڕۆکی دەق بە ڕاستەوخۆ',
      sectionNameHint: 'ناوی بەش یان پۆلی خوێندن',
      tagsHint: 'تاگەکان بە کۆما جیابکەرەوە (نموونە: ڕێساکان، وشەکان، خوێندنەوە)',
      descriptionHint: 'وەسفی وردەکاری بۆ ماددەی فێرکاری',
      fileTooLarge: 'فایلەکە زۆر گەورەیە. لەگەڵی زۆر 50 مێگابایت',
      invalidFileType: 'جۆری فایل پشتگیری ناکرێت',
      materialUploaded: 'ماددەکە بە سەرکەوتوویی بارکرا',
      errorUploadingMaterial: 'هەڵەیەک ڕوویدا لە بارکردنی ماددە',
      draftSaved: 'ڕەشنووسەکە پاشەکەوتکرا',
      errorSavingDraft: 'هەڵەیەک ڕوویدا لە پاشەکەوتکردنی ڕەشنووس',

      // Exams page
      addExam: 'زیادکردنی تاقیکردنەوە',
      editExam: 'دەستکاریکردنی تاقیکردنەوە',
      deleteExam: 'سڕینەوەی تاقیکردنەوە',
      viewExam: 'بینینی تاقیکردنەوە',
      examTitle: 'ناونیشانی تاقیکردنەوە',
      examDescription: 'وەسفی تاقیکردنەوە',
      difficulty: 'قورسایی',
      duration: 'ماوە (خولەک)',
      startDate: 'بەرواری دەستپێک',
      endDate: 'بەرواری کۆتایی',
      passingScore: 'نمرەی پێویست بۆ سەرکەوتن',
      attemptsAllowed: 'ژمارەی هەوڵەکان',
      showResults: 'پیشاندانی ئەنجامەکان',
      allowReview: 'ڕێگەدانی پێداچوونەوە',
      randomizeQuestions: 'ڕێکخستنی پرسیارەکان بە شێوەیەکی هەڕەمەکی',
      timeLimit: 'سنووری کات',
      examStatus: 'دۆخ',
      draft: 'ڕەشنووس',
      examActive: 'چالاک',
      examCompleted: 'تەواوکراو',
      archived: 'هەڵگیراو',
      easy: 'ئاسان',
      medium: 'مامناوەند',
      hard: 'قورس',
      searchExams: 'گەڕان بۆ تاقیکردنەوەکان',
      filterByDifficulty: 'فلتەرکردن بەپێی قورسایی',
      filterByStatus: 'فلتەرکردن بەپێی دۆخ',

      // Create exam page
      basicInformation: 'زانیاریە سەرەکییەکان',
      description: 'وەسف',
      titleRequired: 'ناونیشان پێویستە',
      difficultyRequired: 'ئاستی قورسایی پێویستە',
      durationRequired: 'ماوە پێویستە',
      publishExam: 'بڵاوکردنەوەی تاقیکردنەوە',
      questions: 'پرسیارەکان',
      addQuestion: 'زیادکردنی پرسیار',
      questionText: 'دەقی پرسیار',
      questionType: 'جۆری پرسیار',
      multipleChoice: 'هەڵبژاردنی فرە',
      trueFalse: 'ڕاست و هەڵە',
      points: 'نمرەکان',
      options: 'هەڵبژاردنەکان',
      addOption: 'زیادکردنی هەڵبژاردن',
      correctAnswer: 'وەڵامی ڕاست',
      questionRequired: 'دەقی پرسیار پێویستە',
      atLeastTwoOptions: 'دەبێت لانیکەم دوو هەڵبژاردن هەبێت',
      completeAllQuestions: 'تکایە هەموو پرسیارەکان تەواو بکە',
      examPublished: 'تاقیکردنەوەکە بە سەرکەوتوویی بڵاوکرایەوە',
      addAtLeastOneQuestion: 'دەبێت لانیکەم یەک پرسیار زیاد بکرێت',
      minutes: 'خولەک',

      // Exam results
      examResults: 'ئەنجامی تاقیکردنەوە',
      selectExam: 'هەڵبژاردنی تاقیکردنەوە',
      totalParticipants: 'کۆی بەشداربووان',
      passedStudents: 'قوتابی سەرکەوتووەکان',
      failedStudents: 'قوتابی شکست خواردووەکان',
      exportResults: 'هەناردەی ئەنجامەکان',
      studentName: 'ناوی قوتابی',
      score: 'نمرە',
      percentage: 'لەسەدی',
      attemptNumber: 'ژمارەی هەوڵ',
      startTime: 'کاتی دەستپێک',
      endTime: 'کاتی کۆتایی',
      attemptStatus: 'دۆخ',
      inProgress: 'لە پڕۆسەدا',
      attemptCompleted: 'تەواوکراو',
      abandoned: 'پەرێنراو',

      // Additional exam results
      viewExamResults: 'بینینی ئەنجامی تاقیکردنەوە',
      backToExams: 'گەڕانەوە بۆ تاقیکردنەوەکان',
      chooseExam: 'هەڵبژاردنی تاقیکردنەوە',
      noResults: 'هیچ ئەنجامێک نییە',
      noResultsDescription: 'هیچ ئەنجامێک بۆ ئەم تاقیکردنەوەیە نەدۆزرایەوە',
      exportFeature: 'تایبەتمەندی هەناردەکردن لە پڕۆسەی پەرەپێداندایە',
      viewAttemptDetails: 'بینینی وردەکاری هەوڵ',
      attemptDetailsStudent: 'بینینی وردەکاری هەوڵی قوتابی',

      // Messages
      loginSuccess: 'بە سەرکەوتوویی چوویتە ژوورەوە',
      logoutSuccess: 'بە سەرکەوتوویی چوویتە دەرەوە',
      fillAllFields: 'تکایە هەموو خانەکان پڕ بکەرەوە',
      operationSuccess: 'کردارەکە بە سەرکەوتوویی تەواو بوو',
      operationFailed: 'کردارەکە شکستی هێنا',
      confirmDelete: 'دڵنیای لە سڕینەوە؟',
      confirmAction: 'دڵنیای لەم کردارە؟',
      yes: 'بەڵێ',
      no: 'نەخێر',

      // General
      profile: 'پرۆفایل',
      role: 'ڕۆڵ',
      logout: 'چوونە دەرەوە',
      close: 'داخستن',
      cancel: 'پاشگەزبوونەوە',
      save: 'پاشەکەوتکردن',
      edit: 'دەستکاریکردن',
      delete: 'سڕینەوە',
      view: 'بینین',
      download: 'داگرتن',
      search: 'گەڕان',
      filter: 'فلتەرکردن',
      clear: 'سڕینەوە',
      submit: 'ناردن',
      back: 'گەڕانەوە',
      next: 'دواتر',
      previous: 'پێشوو',
      finish: 'تەواوکردن',

      // Additional translations
      required: 'پێویستە',
      passwordRequired: 'وشەی نهێنی پێویستە',
      fullName: 'ناوی تەواو',
      nameRequired: 'ناو پێویستە',
      emailRequired: 'ئیمەیڵ پێویستە',
      createAccount: 'دروستکردنی هەژمارێکی نوێ',
      createAccountSuccess: 'هەژمارەکە بە سەرکەوتوویی دروست بوو. تکایە ئیمەیڵەکەت پشتڕاست بکەرەوە',
      googleLoginComingSoon: 'چوونە ژوورەوە بە Google بەم زووانە زیاد دەکرێت',
      fillAllFieldsRequired: 'تکایە هەموو خانەکان پڕ بکەرەوە'
    }
  }

  function getText(key: string): string {
    const langTexts = texts[currentLanguage.value]
    return (langTexts as Record<string, string>)[key] || key
  }

  function setLanguage(lang: Language) {
    currentLanguage.value = lang
    localStorage.setItem('preferred-language', lang)
  }

  // Initialize from localStorage
  const savedLang = localStorage.getItem('preferred-language') as Language
  if (savedLang && (savedLang === 'ar' || savedLang === 'ckb')) {
    currentLanguage.value = savedLang
  }

  return {
    currentLanguage,
    getText,
    setLanguage
  }
})
